ietf/urls.py
# Copyright The IETF Trust 2007, 2009, All Rights Reserved

import django
from django.conf.urls.defaults import patterns, include, handler404, handler500
from django.contrib import admin

from ietf.iesg.feeds import IESGAgenda
from ietf.idtracker.feeds import DocumentComments, InLastCall
from ietf.ipr.feeds import LatestIprDisclosures
from ietf.proceedings.feeds import LatestWgProceedingsActivity
from ietf.liaisons.feeds import Liaisons

from ietf.idtracker.sitemaps import IDTrackerMap, DraftMap
from ietf.liaisons.sitemaps import LiaisonMap
from ietf.ipr.sitemaps import IPRMap
from ietf.announcements.sitemaps import NOMCOMAnnouncementsMap

from django.conf import settings

admin.autodiscover()
admin.site.disable_action('delete_selected')

feeds = {
    'iesg-agenda': IESGAgenda,
    'last-call': InLastCall,
    'comments': DocumentComments,
    'ipr': LatestIprDisclosures,
    'liaison': Liaisons,
    'wg-proceedings' : LatestWgProceedingsActivity
}

sitemaps = {
    'idtracker': IDTrackerMap,
    'drafts': DraftMap,
    'liaison': LiaisonMap,
    'ipr': IPRMap,
    'nomcom-announcements': NOMCOMAnnouncementsMap,
}

urlpatterns = patterns('',
    (r'^feed/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
              { 'feed_dict': feeds}),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index',
              { 'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap',
              {'sitemaps': sitemaps}),
    (r'^ann/', include('ietf.announcements.urls')),
    (r'^idtracker/', include('ietf.idtracker.urls')),
    (r'^drafts/', include('ietf.idindex.urls')),
    (r'^iesg/', include('ietf.iesg.urls')),
    (r'^liaison/', include('ietf.liaisons.urls')),
    (r'^list/', include('ietf.mailinglists.urls')),
    (r'^(?P<path>public)/', include('ietf.redirects.urls')),
    (r'^ipr/', include('ietf.ipr.urls')),
    (r'^meeting/', include('ietf.meeting.urls')),
    (r'^accounts/', include('ietf.ietfauth.urls')),
    (r'^doc/', include('ietf.idrfc.urls')),
    (r'^wg/', include('ietf.wginfo.urls')),
    (r'^cookies/', include('ietf.cookies.urls')),
    (r'^submit/', include('ietf.submit.urls')),

    (r'^$', 'ietf.idrfc.views.main'),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    ('^admin/', include(admin.site.urls)),

    # Google webmaster tools verification url
    (r'^googlea30ad1dacffb5e5b.html', 'django.views.generic.simple.direct_to_template', { 'template': 'googlea30ad1dacffb5e5b.html' }),
)

if settings.SERVER_MODE in ('development', 'test'):
    urlpatterns += patterns('',
        (r'^(?P<path>(?:images|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^(?P<path>robots\.txt)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^_test500/$', lambda x: None),
	)

liaisons/urls.py
# Copyright The IETF Trust 2007, All Rights Reserved

from django.conf.urls.defaults import patterns
from ietf.liaisons.models import LiaisonDetail

info_dict = {
    'queryset': LiaisonDetail.objects.all().order_by("-submitted_date"),
}

# there's an opportunity for date-based filtering.
urlpatterns = patterns('django.views.generic.list_detail',
     (r'^$', 'object_list', info_dict),
     (r'^(?P<object_id>\d+)/$', 'object_detail', info_dict),
)

urlpatterns += patterns('django.views.generic.simple',
     (r'^help/$', 'direct_to_template', {'template': 'liaisons/help.html'}),
     (r'^help/fields/$', 'direct_to_template', {'template': 'liaisons/field_help.html'}),
     (r'^help/from_ietf/$', 'direct_to_template', {'template': 'liaisons/guide_from_ietf.html'}),
     (r'^help/to_ietf/$', 'direct_to_template', {'template': 'liaisons/guide_to_ietf.html'}),
     (r'^managers/$', 'redirect_to', { 'url': 'http://www.ietf.org/liaison/managers.html' })
)

sec/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    url(r'^$', direct_to_template, {'template': 'main.html'}, name="home"),
    (r'^admin/', include(admin.site.urls)),
    (r'^areas/', include('sec.areas.urls')),
    (r'^drafts/', include('sec.drafts.urls')),
    (r'^groups/', include('sec.groups.urls')),
    (r'^liaison/', include('sec.liaison.urls')),
    (r'^roles/', include('sec.roles.urls')),
    (r'^rolodex/', include('sec.rolodex.urls')),
    (r'^interim/', include('sec.interim.urls')),
    (r'^proceedings/', include('sec.proceedings.urls')),
)

urls.py
# Copyright The IETF Trust 2007, 2009, All Rights Reserved

import django
from django.conf.urls.defaults import patterns, include, handler404, handler500

from ietf.iesg.feeds import IESGAgenda
from ietf.idtracker.feeds import DocumentComments, InLastCall
from ietf.ipr.feeds import LatestIprDisclosures
from ietf.proceedings.feeds import LatestWgProceedingsActivity
from ietf.liaisons.feeds import Liaisons

from ietf.idtracker.sitemaps import IDTrackerMap, DraftMap
from ietf.liaisons.sitemaps import LiaisonMap
from ietf.ipr.sitemaps import IPRMap
from ietf.announcements.sitemaps import NOMCOMAnnouncementsMap

from ietf.idrfc.views import main

from django.conf import settings

feeds = {
    'iesg-agenda': IESGAgenda,
    'last-call': InLastCall,
    'comments': DocumentComments,
    'ipr': LatestIprDisclosures,
    'liaison': Liaisons,
    'wg-proceedings' : LatestWgProceedingsActivity
}

sitemaps = {
    'idtracker': IDTrackerMap,
    'drafts': DraftMap,
    'liaison': LiaisonMap,
    'ipr': IPRMap,
    'nomcom-announcements': NOMCOMAnnouncementsMap,
}

urlpatterns = patterns('',
      (r'^feed/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
		{ 'feed_dict': feeds}),
      (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index',
		{ 'sitemaps': sitemaps}),
      (r'^sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap',
		{'sitemaps': sitemaps}),
      (r'^ann/', include('ietf.announcements.urls')),
      (r'^idtracker/', include('ietf.idtracker.urls')),
      (r'^drafts/', include('ietf.idindex.urls')),
      (r'^iesg/', include('ietf.iesg.urls')),
      (r'^liaison/', include('ietf.liaisons.urls')),
      (r'^list/', include('ietf.mailinglists.urls')),
      (r'^(?P<path>public|cgi-bin)/', include('ietf.redirects.urls')),
      (r'^ipr/', include('ietf.ipr.urls')),
      (r'^meeting/', include('ietf.meeting.urls')),
      (r'^accounts/', include('ietf.ietfauth.urls')),
      (r'^doc/', include('ietf.idrfc.urls')),
      (r'^wg/', include('ietf.wginfo.urls')),

      (r'^$', main),

     # Google webmaster tools verification url
     (r'^googlea30ad1dacffb5e5b.html', 'django.views.generic.simple.direct_to_template', { 'template': 'googlea30ad1dacffb5e5b.html' }),
)

if settings.SERVER_MODE in ('development', 'test'):
    urlpatterns += patterns('',
        (r'^(?P<path>(?:images|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^_test500/$', lambda x: None),
	)

liaisons/models.py
# Copyright The IETF Trust 2007, All Rights Reserved

from django.db import models
from ietf.idtracker.models import Acronym,PersonOrOrgInfo
from django.core.exceptions import ObjectDoesNotExist

class LiaisonPurpose(models.Model):
    purpose_id = models.AutoField(primary_key=True)
    purpose_text = models.CharField(blank=True, max_length=50)
    def __str__(self):
	return self.purpose_text
    class Meta:
        db_table = 'liaison_purpose'
    class Admin:
	pass

class FromBodies(models.Model):
    from_id = models.AutoField(primary_key=True)
    body_name = models.CharField(blank=True, max_length=35)
    poc = models.ForeignKey(PersonOrOrgInfo, db_column='poc', null=True)
    is_liaison_manager = models.BooleanField()
    other_sdo = models.BooleanField()
    email_priority = models.IntegerField(null=True, blank=True)
    def __str__(self):
	return self.body_name
    class Meta:
        db_table = 'from_bodies'
    class Admin:
	pass

class LiaisonDetail(models.Model):
    detail_id = models.AutoField(primary_key=True)
    person = models.ForeignKey(PersonOrOrgInfo, db_column='person_or_org_tag')
    submitted_date = models.DateField(null=True, blank=True)
    last_modified_date = models.DateField(null=True, blank=True)
    from_id = models.IntegerField(null=True, blank=True)
    to_body = models.CharField(blank=True, max_length=255)
    title = models.CharField(blank=True, max_length=255)
    response_contact = models.CharField(blank=True, max_length=255)
    technical_contact = models.CharField(blank=True, max_length=255)
    purpose_text = models.TextField(blank=True, db_column='purpose')
    body = models.TextField(blank=True)
    deadline_date = models.DateField(null=True, blank=True)
    cc1 = models.TextField(blank=True)
    # unclear why cc2 is a CharField, but it's always
    # either NULL or blank.
    cc2 = models.CharField(blank=True, max_length=50)
    submitter_name = models.CharField(blank=True, max_length=255)
    submitter_email = models.CharField(blank=True, max_length=255)
    by_secretariat = models.IntegerField(null=True, blank=True)
    to_poc = models.CharField(blank=True, max_length=255)
    to_email = models.CharField(blank=True, max_length=255)
    purpose = models.ForeignKey(LiaisonPurpose)
    replyto = models.CharField(blank=True, max_length=255)
    def __str__(self):
	return self.title or "<no title>"
    def from_body(self):
	"""The from_id field is a foreign key for either
	FromBodies or Acronyms, depending on whether it's
	the IETF or not.  There is no flag field saying
	which, so we just try it.  If the index values
	overlap, then this function will be ambiguous
	and will return the value from FromBodies.  Current
	acronym IDs start at 925 so the day of reckoning
	is not nigh."""
	try:
	    from_body = FromBodies.objects.get(pk=self.from_id)
	    return from_body.body_name
	except ObjectDoesNotExist:
	    pass
	try:
	    acronym = Acronym.objects.get(pk=self.from_id)
	    if acronym.area_set.count():
		type = "AREA"
	    else:
		type = "WG"
	    return "IETF %s %s" % ( acronym.acronym.upper(), type )
	except ObjectDoesNotExist:
	    pass
	return "<unknown body %d>" % self.from_id
    def from_email(self):
	"""If there is an entry in from_bodies, it has
	the desired email priority.  However, if it's from
	an IETF WG, there is no entry in from_bodies, so
	default to 1."""
	try:
	    from_body = FromBodies.objects.get(pk=self.from_id)
	    email_priority = from_body.email_priority
	except FromBodies.DoesNotExist:
	    email_priority = 1
	return self.person.emailaddress_set.all().get(priority=email_priority)
    def get_absolute_url(self):
	return '/liaison/%d/' % self.detail_id
    class Meta:
        db_table = 'liaison_detail'
    class Admin:
	pass

# This table is not used by any code right now, and according to Glen,
# probably not currently (Aug 2009) maintained by the secretariat.
#class SDOs(models.Model):
#    sdo_id = models.AutoField(primary_key=True)
#    sdo_name = models.CharField(blank=True, max_length=255)
#    def __str__(self):
#	return self.sdo_name
#    def liaisonmanager(self):
#	try:
#	    return self.liaisonmanagers_set.all()[0]
#	except:
#	    return None
#    class Meta:
#        db_table = 'sdos'
#    class Admin:
#	pass

# This table is not used by any code right now, and according to Glen,
# probably not currently (Aug 2009) maintained by the secretariat.
#class LiaisonManagers(models.Model):
#    person = models.ForeignKey(PersonOrOrgInfo, db_column='person_or_org_tag')
#    email_priority = models.IntegerField(null=True, blank=True)
#    sdo = models.ForeignKey(SDOs)
#    def email(self):
#	try:
#	    return self.person.emailaddress_set.get(priority=self.email_priority)
#	except ObjectDoesNotExist:
#	    return None
#    class Meta:
#        db_table = 'liaison_managers'

# This table is not used by any code right now.
#class LiaisonsInterim(models.Model):
#    title = models.CharField(blank=True, max_length=255)
#    submitter_name = models.CharField(blank=True, max_length=255)
#    submitter_email = models.CharField(blank=True, max_length=255)
#    submitted_date = models.DateField(null=True, blank=True)
#    from_id = models.IntegerField(null=True, blank=True)
#    def __str__(self):
#	return self.title
#    class Meta:
#        db_table = 'liaisons_interim'
#    class Admin:
#	pass

class Uploads(models.Model):
    file_id = models.AutoField(primary_key=True)
    file_title = models.CharField(blank=True, max_length=255)
    person = models.ForeignKey(PersonOrOrgInfo, db_column='person_or_org_tag')
    file_extension = models.CharField(blank=True, max_length=10)
    detail = models.ForeignKey(LiaisonDetail)
    def __str__(self):
	return self.file_title
    class Meta:
        db_table = 'uploads'

# empty table
#class SdoChairs(models.Model):
#    sdo = models.ForeignKey(SDOs)
#    person = models.ForeignKey(PersonOrOrgInfo, db_column='person_or_org_tag')
#    email_priority = models.IntegerField(null=True, blank=True)
#    class Meta:
#        db_table = 'sdo_chairs'
#    class Admin:
#	pass

# changes done by convert-096.py:changed maxlength to max_length
# removed core
# removed edit_inline
# removed num_in_admin
# removed raw_id_admin

sec/liaison/models.py
from django.db import models
from sec.core.models import PersonOrOrgInfo

class FromBodies(models.Model):
    from_id = models.AutoField(primary_key=True)
    body_name = models.CharField(blank=True, max_length=35)
    poc = models.ForeignKey(PersonOrOrgInfo, db_column='poc', null=True)
    is_liaison_manager = models.BooleanField()
    other_sdo = models.BooleanField()
    email_priority = models.IntegerField(null=True, blank=True)
    def __unicode__(self):
	return self.body_name
    class Meta:
        db_table = 'from_bodies'
        ordering = ['body_name']

sec/liaison/forms.py
import re
from django import forms
from models import FromBodies

class FromBodiesForm(forms.Form):
    name = forms.CharField(max_length=35)

    def clean_name(self):
        # get name, strip leading and trailing spaces
        name = self.cleaned_data.get('name', '').strip()
        # ensure name doesn't already exist in the table, case insensitive
        if FromBodies.objects.filter(body_name__iexact=name).count() > 0:
            raise forms.ValidationError("This name already exists!")
        # check for invalid characters
        r1 = re.compile(r'[\w\-\.\/ ]+$')
        if not r1.match(name):
            # raise forms.ValidationError("Only alphanumeric characters and '-', '.', '/' are allowed!") 
            raise forms.ValidationError("Enter a valid name.") 
        return name

sec/liaison/views.py
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from session_messages import create_message
from models import FromBodies
from forms import FromBodiesForm

def add_liaison(request):
    """ 
    Displays the add liaisons form for models.FromBodies

    Shows a list of existing records and allows user to add new records to :model:`models.FromBodies`
    
    Name field validation

    * stripped of leading and trailing spaces
    * checks to see the name doesn't already exist in the dbase, case insensitive
    * allows only alphanumeric, spaces and '-', '.', '/' characters

    **Templates:**

    * ``liaison/add_liaisons.html``

    **Variables:**

    * ``from_bodies : query set of FromBodies where poc = 0 or poc = NULL``
    * ``form : an instance of FromBodiesForm``


    """
    if request.method == 'POST':
        form = FromBodiesForm(request.POST)
        if form.is_valid():
            # hard coding defaults
            # this would be unnecessary if defaults can be defined in the model
            # "poc" field is absent (NULL), which is allowed by the model
            name = form.cleaned_data['name']
            f = FromBodies(body_name=name,
                    is_liaison_manager=False,
                    other_sdo='1',
                    email_priority='1')
            f.save()
            # we are expecting anonymous users for this view
            # cannot use message_set with anonymous users so need redirect
            if request.user.is_authenticated():
                request.user.message_set.create(message="New Liaison, %s, added successfully!" % name)
            else:
                create_message(request, 'New Liaison, %s, added successfully!' % name)
                # form.reset()
            url = reverse('sec.liaison.views.add_liaison')
            return HttpResponseRedirect(url)
    else:
        form = FromBodiesForm()
    # only show those records where poc=0 or poc=NULL
    from_bodies = FromBodies.objects.filter(Q(poc__isnull=True) | Q(poc=0))
    return render_to_response(
        "liaison/add_liaison.html",
        {'from_bodies' : from_bodies, 'form': form, },
        RequestContext(request, {}),
    )

templates/liaisons/field_help.html
{# Copyright The IETF Trust 2007, All Rights Reserved #}
{% extends "base.html" %}{% load ietf_filters %}

{% block title %}Liaison Statement Management Tool Field Help{% endblock %}

{% block content %}
<center><font size=+2>Liaison Statement Management Tool<br>Field Help</font></center>
<br>
The table below provides descriptions of the fields included in the 
liaison statement submission form, and suggestions for completing them,
where appropriate.  Additional materials that may be useful in 
completing this form can be found in the following documents:
<br><br>
<ul>
<li><a href="/liaison/help/to_ietf/">Liaison Statements to the IETF: Guidelines for Completing the "To:" and "Cc:" Fields </a>
<li><a href="/liaison/help/from_ietf/">Liaison Statements from the IETF: Guidelines for Completing the "Cc:" Field</a>
<li><a href="/wg/">Active IETF Working Groups</a>
<li><a href="/liaison/managers/">IETF Liaison Managers</a>
</ul>
For definitive information on generating liaison statements, please
see <a href="{{ "4053"|rfcurl }}">RFC 4053 (BCP 103) "Procedures for Handling Liaison Statements to and from the IETF."</a><br><br>
<table cellpadding="3" cellspacing="0" border="1">
  <tr align="center">
    <td><b>Field</b></td>
    <td><b>Sub-field</b></td>
    <td><b>Description</b></td>
    <td><b>Comments</b></td></tr>
  <tr>
    <td rowspan="2">From:</td>
    <td>Organization:</td>
    <td>The organization submitting the liaison statement.</td>
    <td>The field is filled in automatically.</td></tr>
  <tr>
    <td>Submitter:</td>
    <td>The name and e-mail address of the person submitting the liaison statement.</td>  
    <td>The field is filled in automatically.</td></tr>
  <tr>
    <td>Reply-To:</td>
    <td>&nbsp</td>
    <td>The e-mail address(es) that will be inserted in the "To:" field when a recipient hits the "Reply" button on the message.
</td>
    <td>Mandatory<br> Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp; Name &lt;e-mail address&gt</td></tr
  <tr>
    <td rowspan="2">To:</td>
    <td>Organization:</td>
    <td>The name of the organization (and sub-group, if applicable) to which the liaison statement is being sent.</td>
    <td>Mandatory <br>Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp;SDO/Sub-group</td></tr>
  <tr>
    <td>POC(s):</td>
    <td>The e-mail address(es) of the recipient(s) of the liaison statement, separated by commas.</td>  
    <td>Mandatory<br> Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp; Name &lt;e-mail address&gt</td></tr>
  <tr>
    <td>Cc:</td>
    <td>&nbsp</td>
    <td>The e-mail address(es) of the copy recipient(s) of the liaison statement, separated by commas.</td>
    <td>Optional<br> Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp; Name &lt;e-mail address&gt</td></tr>
  <tr>
    <td>Title:</td>
    <td>&nbsp</td>
    <td>The title of the liaison statement.</td>
    <td>Mandatory</td></tr>
  <tr>
    <td>Response Contact:</td>
    <td>&nbsp</td>
    <td>The e-mail address(es) to which any response should be sent, separated by commas.</td>
    <td>Optional<br> Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp; Name &lt;e-mail address&gt</td></tr>
  <tr>
    <td>Technical Contact:</td>
    <td>&nbsp</td>
    <td>The e-mail address(es) of individuals or lists that may be contacted for clarification of the liaison statement, separated by commas.</td>
    <td>Optional<br> Suggested Format:<br>&nbsp;&nbsp;&nbsp;&nbsp; Name &lt;e-mail address&gt</td></tr>
  <tr>
    <td>Purpose:</td>
    <td>&nbsp</td>
    <td>The intent of the liaison statement.  Normally, one of four choices: (a) For action, (b) For comment, (c) For information, (d) Response.</td>
    <td>Optional<br>The submitter selects one of the four choices, or selects "Other," and indicates the intent.</td></tr>  <tr>
    <td>Deadline:</td>
    <td>&nbsp</td>
    <td>The date by which a comment or action is required.</td>
    <td>Mandatory if the purpose is "For comment" or "For action." Otherwise, optional. </td></tr>
 <tr>
    <td>Body:</td>
    <td>&nbsp</td>
    <td>The text of the liaison statement.</td>
    <td>Mandatory if there are no attachments.
<br>Optional if the text of the liaison statement is provided in an attachment.</td></tr>

</table>
{% endblock %}

templates/liaisons/liaisondetail_detail.html
{# Copyright The IETF Trust 2007, All Rights Reserved #}
{# no template, this page has its own look. #}
{% load ietf_filters %}
<html>
<head><title>Liaison Statement Detail:
{% include 'liaisons/liaison_title.html' %}</title>
<style type="text/css">

a:link, a:visited {
  border-bottom:1px dotted #69f;
  color:blue;
  text-decoration:none;
  }
a:visited {
  border-bottom:1px dotted #969;
  color:#939;
  }
a:hover {
  border-bottom:1px dotted #f00;
  color:#f00;
  }
</style>
</head>
<body topmargin='0' bottommargin='0' leftmargin='0' rightmargin='0' background='/images/back_dot.gif'>
<table bgcolor="#F4F2F2" border=2 cellpadding=0 cellspacing=0 width='671' height="300" align='center'>
  <tr valign="top"><td>
      <table width="100%" height='100%' border=0 cellpadding=0 cellspacing=0 bgcolor="#FFFFFF">
          <tr valign="top"><td><img src="/images/liaison_title.gif" height="96" border="0"></td></tr>
          <tr valign="top"><td>

<center><h3>
{% include 'liaisons/liaison_title.html' %}
</h3></center>
  {% if not object.by_secretariat %}
  <blockquote>
  <table cellspacing="3" bgcolor="cccc99" width="600">
  <tr>
  <td bgcolor="#efefef" width="25%">Submission Date: </td><td width="75%"><pre>{{ object.submitted_date }}</pre></td></tr>
  <tr>
  <td bgcolor="#efefef" width="25%">From: </td><td width="75%"><pre>{{ object.from_body|escape }} (<a href="mailto:{{ object.from_email|fix_ampersands }}">{{ object.person|escape }}</a>)</pre></td></tr>
  <tr>
  <td bgcolor="#efefef">To: </td><td><pre>{{ object.to_body|escape }} ({{ object.to_poc|parse_email_list|safe }})</pre></td></tr>
  <tr>
  <td bgcolor="#efefef">Cc:</td><td><pre>{{ object.cc1|parse_email_list|make_one_per_line|safe }}</pre></td></tr>
  <tr>
  <td bgcolor="#efefef">Response Contact:</td>
  <td>
<pre>{{ object.response_contact|parse_email_list|make_one_per_line|safe }}</pre>
  </td></tr>
  <tr>
  <td bgcolor="#efefef">Technical Contact:</td>
  <td>
<pre>{{ object.technical_contact|parse_email_list|make_one_per_line|safe }}</pre></td>
  </tr>
  <tr>
  <td bgcolor="#efefef">Purpose:</td><td><pre>{% if object.purpose_text %}{{ object.purpose_text }}{% else %}{{ object.purpose }}{% endif %}</pre></td></tr>
  <tr>
  <td bgcolor="#efefef">Deadline:</td><td><pre>{{ object.deadline_date }}</pre></td></tr>
  <tr>
  <td bgcolor="#efefef">Body:</td><td><pre>{{ object.body|wordwrap:"71"|escape }}</pre></td></tr>
  </table>
  </blockquote>
  {% endif %}
<hr>
<blockquote>
<h3>Attached Document(s)</h3>
{% if object.uploads_set.count %}
<ul>
{% for file in object.uploads_set.all %}
<li><a href="https://datatracker.ietf.org/documents/LIAISON/file{{ file.file_id }}{{ file.file_extension }}">{{ file.file_title }}</a><br>
{% endfor %}
</ul>
{% else %}
NONE
{% endif %}
</blockquote>

</td></tr></table>
</body>
</html>